name: genesis_shell
description: "Next generation mobile/desktop shell"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  expidus:
    git:
      url: https://github.com/ExpidusOS/libexpidus.git
      ref: 6c0f634413a6289a8edaf4eb37ca4cc318eaa633
  miso:
    git:
      url: https://github.com/ExpidusOS/miso.git
      ref: bd612536c8a53011a963391ade7f576139ed569b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
