name: genesis_shell
description: The next-generation fully featured desktop environment ExpidusOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo_flutter
  gokai:
    git:
      url: https://github.com/ExpidusOS/gokai.git
      ref: 7df0426ece67abe9738eef56475a223bc1411196
      path: packages/gokai
  intl: ^0.18.0
  args: ^2.4.2
  dbus: ^0.7.8
  xdg_directories: ^1.0.0
  flutter_adaptive_scaffold: ^0.1.6
  provider: ^6.0.5

dependency_overrides:
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: eb140908dd2435afdf6208cb84bd37db840b46df
      path: packages/libtokyo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper/desktop/
    - assets/wallpaper/mobile/
