name: genesis_shell
description: The next-generation fully featured desktop environment ExpidusOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 49f377e207802f1a39737ec1331fd1949cd4b5b9
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 49f377e207802f1a39737ec1331fd1949cd4b5b9
      path: packages/libtokyo_flutter
  gokai:
    git:
      url: https://github.com/ExpidusOS/gokai.git
      ref: d1076fcfcd27467e2d75f78ca46b89a99230f4f3
      path: packages/gokai
  intl: ^0.18.0
  args: ^2.4.2
  dbus: ^0.7.8
  xdg_directories: ^1.0.0
  flutter_adaptive_scaffold: ^0.1.6
  provider: ^6.0.5

dependency_overrides:
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 49f377e207802f1a39737ec1331fd1949cd4b5b9
      path: packages/libtokyo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper/desktop/
    - assets/wallpaper/mobile/
