name: genesis_shell
description: "Next generation mobile/desktop shell"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  expidus:
    git:
      url: https://github.com/ExpidusOS/libexpidus.git
      ref: df9b48ac5e9168f148ed1cfe2e4df0d3bd0664f1
  miso:
    git:
      url: https://github.com/ExpidusOS/miso.git
      ref: ddd36cb57c62ded47335a1a52d96547c543dda64

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper/desktop/
    - assets/wallpaper/mobile/
